import { EventCard } from "@/components/events/event-card"

const events = [
  {
    id: 1,
    title: "Versova Beach Cleanup Drive",
    description: "Join us for a massive beach cleanup at Versova Beach. We'll provide all equipment and refreshments.",
    date: "2024-12-15",
    time: "06:00",
    duration: "4 hours",
    location: "Versova Beach, Mumbai",
    organizer: "Mumbai Coastal Guardians",
    participants: 45,
    maxParticipants: 60,
    difficulty: "Easy",
    type: "Beach Cleanup",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Beach Cleanup", "Plastic Removal", "Community"],
    rewards: 150,
    distance: "2.3 km",
  },
  {
    id: 2,
    title: "Mangrove Restoration Project",
    description:
      "Help restore the mangrove ecosystem at Mahim Creek. Plant saplings and learn about marine biodiversity.",
    date: "2024-12-18",
    time: "07:00",
    duration: "6 hours",
    location: "Mahim Creek, Mumbai",
    organizer: "Green Mumbai Initiative",
    participants: 23,
    maxParticipants: 30,
    difficulty: "Medium",
    type: "Mangrove Restoration",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Restoration", "Biodiversity", "Education"],
    rewards: 200,
    distance: "5.1 km",
  },
  {
    id: 3,
    title: "Plastic Awareness Workshop",
    description:
      "Educational workshop on plastic pollution and its impact on marine life. Includes hands-on activities.",
    date: "2024-12-22",
    time: "10:00",
    duration: "3 hours",
    location: "Community Center, Bandra",
    organizer: "Ocean Warriors",
    participants: 12,
    maxParticipants: 25,
    difficulty: "Easy",
    type: "Awareness Workshop",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Education", "Awareness", "Workshop"],
    rewards: 100,
    distance: "3.7 km",
  },
  {
    id: 4,
    title: "Coral Conservation Dive",
    description: "Underwater coral restoration activity for certified divers. Help transplant coral fragments.",
    date: "2024-12-25",
    time: "08:00",
    duration: "5 hours",
    location: "Malvan, Maharashtra",
    organizer: "Dive for Conservation",
    participants: 8,
    maxParticipants: 12,
    difficulty: "Hard",
    type: "Coral Conservation",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Diving", "Coral", "Advanced"],
    rewards: 300,
    distance: "180 km",
  },
  {
    id: 5,
    title: "Coastal Plastic Collection",
    description: "Systematic plastic waste collection along the Juhu coastline using scientific methods.",
    date: "2024-12-28",
    time: "06:30",
    duration: "4 hours",
    location: "Juhu Beach, Mumbai",
    organizer: "Scientific Cleanup Collective",
    participants: 34,
    maxParticipants: 50,
    difficulty: "Medium",
    type: "Plastic Collection",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Research", "Data Collection", "Science"],
    rewards: 175,
    distance: "4.2 km",
  },
  {
    id: 6,
    title: "Marine Life Photography Walk",
    description: "Document marine biodiversity while cleaning the shoreline. Bring your camera and help science!",
    date: "2024-12-30",
    time: "05:30",
    duration: "3 hours",
    location: "Worli Sea Face, Mumbai",
    organizer: "Nature Photographers Guild",
    participants: 18,
    maxParticipants: 20,
    difficulty: "Easy",
    type: "Beach Cleanup",
    image: "/placeholder.svg?height=200&width=400",
    tags: ["Photography", "Documentation", "Art"],
    rewards: 125,
    distance: "1.8 km",
  },
]

export function EventGrid() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {events.map((event) => (
        <EventCard key={event.id} event={event} />
      ))}
    </div>
  )
}
